### ISSUE TITLE
pymatgen compatibiilty issue

### ISSUE THREAD

**Issue by similt** [SMTG-UCL/doped#15]
When I tried to get phase diagram using 
cpa.calculate_chempots()

I am getting error: 

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_623835/2503364578.py in <module>
----> 1 cpa.calculate_chempots()

~/Downloads/cplap/doped/doped/competing_phases.py in calculate_chempots(self, csv_fname)
    393             # presumably checks if the phase is intrinsic
    394             if set(Composition(d['formula']).elements).issubset(self.bulk_composition.elements):
--> 395                 pd_entries_intrinsic.append(e)
    396                 if e.composition == self.bulk_composition:
    397                     self.bulk_pde = e

~/Downloads/anaconda3/lib/python3.9/site-packages/pymatgen/analysis/phase_diagram.py in __init__(self, entries, elements, computed_data)
    357         self.entries = entries
    358         if computed_data is None:
--> 359             computed_data = self._compute()
    360         else:
    361             computed_data = MontyDecoder().process_decoded(computed_data)

~/Downloads/anaconda3/lib/python3.9/site-packages/pymatgen/analysis/phase_diagram.py in _compute(self)
    421         if len(el_refs) != dim:
    422             missing = set(elements).difference(el_refs.keys())
--> 423             raise ValueError(f"There are no entries for the terminal elements: {missing}")
    424 
    425         data = np.array(

ValueError: There are no entries for the terminal elements: {Element O, Element La, Element Mn}

**Comment by brlec** [comment]
Hi!  I'm assuming you got this error in the example jupyter notebook - we've now added the example files and changed the notebook to make it more user friendly. Latest commit to master ([df78149f](https://github.com/SMTG-UCL/doped/commit/df78149f37cbe216528671799ffed341e5f5b6ab)) should fix this. If updating doped doesn't fix it, please let us know :)
