### ISSUE TITLE
Mismatched atomic order causing incorrect kumagai corrections

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/doped#17]
l have been trying to track down a change of results after upgrading doped from an older version (Apil 2022). The results from the kumagai correction are different from before, and I have found this is due to the incorrect `site_maching_indices` extract. 

The problem is down to the fact that the bulk structure and the defect structure appears to have different ordering of the species. In particular, the bulk structure has `Al O Sb` while the defects generated has `Al Sb O`. This change is due to the use of `MPRelaxSet` when preparing the input structure, which includes a standardisation step that may change the ordering of species.

In the old version, the `initial_defect_structure` was used for the kumagai and I had it as the "unrelaxed defect structure". However, in the more recent version the `unrelaxed_defect_structure` takes the precedence. It is generated from the bulk structure, but as I mentioned above, it can have a different ordering of the atoms compared to that used in the actual calculation. Hence, this generates an incorrect `site_maching_indices` needed for kumagai. More confusingly, the `kumagai_loader` saves this structure as `initial_defect_structure`.

A few solutions to this issue:

1. Do we really need to use the `MPRelaxSet`? It reorders the structure, which is OK for database building but perhaps not so for defect calculations. My suggestion is to get rid of it or at least have our own implementation that does a similar thing. 
2. A warning should be printed if the bulk and the defect have different species orderings. 
3. The site matching for kumagai (matching between the bulk and the defect) should be performed using the actual defect structure used in the calculation `initial_defect_structure`, rather than the `unrelaxed_defect_structure`. But this should be really be resolved by guaranteeing the defect structure calculated is really the one that is generated with the same ordering (solving 1).

**Comment by zhubonan** [comment]
> My opinion would be that doped should just be able to recognise if the species ordering differs between the bulk and defect, and just determine the correct site_matching_indices based on this, so no warnings necessary (we already have quite a lot...)

This would be an ideal solution, one could first match "bulk" with the "unrelaxed" then "unrelaxed" with the "initial". This should be more robust than making "bulk" directly with "initial" structure.

**Comment by kavanase** [comment]
Fixed with PR #18 by @zhubonan, now merged to `develop` and soon to be pulled to `main`.
