### ISSUE TITLE
Repository size seems to be very large?

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/doped#26]
I tried to clone the repository for development but it takes a long time with git reporting receiving over 1GB worth of objects and `du -sh` reports a directory size of 1.6 GB.

This is probably due to the large files? I had the impression that the size of the repo is not easy to reduce retrospectively without messing up the commit history. But it may be worth keeping it growing further? It may be useful to move large examples files into dedicated repositories.

**Comment by kavanase** [comment]
Yep the `LOCPOT.gz` test/example files in particular use up a bit of space. I cleaned the `.git` folder of unnecessary records of old test files somewhat recently (https://github.com/SMTG-UCL/doped/commit/f081936fdb3d569b12a59e6b30cf3e9bb1de4e58), which reduced it a bit, but still around 1.6 Gb. 
We shouldn't need to add anymore big files to the repository, and for most users we recommend installation by `pip` or `conda`, so I think this is ok as is?
But worth keeping an eye on as well

**Comment by zhubonan** [comment]
It may be worth adding pre-commit hooks to check for large files https://pre-commit.com/hooks.html?
