### ISSUE TITLE
Could not generate bulk file

### ISSUE THREAD

**Issue by 007szs** [SMTG-UCL/doped#5]
I can get all the defect files  using the python codes in dope_Example_Notebook.ipynb. But this python code can not generate bulk film. That is to say, I want to get a fold named Bulk_Supercell as shown in https://github.com/SMTG-UCL/doped/tree/master/Examples/Bulk_Supercell. Can anyone help me?

**Comment by kavanase** [comment]
HI @007szs 
This is not a component of the `doped` code, you have to generate the bulk supercell structure yourself. You can do this with the pymatgen functions to generate a supercell (with `structure.make_supercell()`; https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.Structure.make_supercell) and convert from primitive to conventional beforehand if needed. So you can then run the bulk cell calculation and name the bulk folder whatever you like, it doesn’t have to be “`Bulk_Supercell`”.

An example for this has now been added to the [example notebook](https://github.com/SMTG-UCL/doped/blob/develop/dope_Example_Notebook.ipynb) with commit #ada67de on the `develop` branch.
I hope this answers your question!

**Comment by 007szs** [comment]
Hi, @kavanase 
My question was fully solved according to you answers. Thanks very much!
