### ISSUE TITLE
standard pip installation does not work....

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/doped#6]
```
~/miniconda3/envs/aiida-1.0-py3/lib/python3.8/site-packages/monty/io.py in zopen(filename, *args, **kwargs)
     41     if ext in (".GZ", ".Z"):
     42         return gzip.open(filename, *args, **kwargs)
---> 43     return io.open(filename, *args, **kwargs)  # pylint: disable=R1732
     44 
     45 

FileNotFoundError: [Errno 2] No such file or directory: '/home/bonan/miniconda3/envs/aiida-1.0-py3/lib/python3.8/site-packages/doped/default_POTCARs.yaml'

```
I think it is because `default_POTCARs.yaml` is not included in the python package....

**Comment by kavanase** [comment]
Thanks for this @zhubonan! This has now been fixed (and tested) with f72b37b06ed036b816edfb0e453291dd06deba18
Merging into master because important fixes have been added to `develop` and no known issues with this branch (also the actual package is still in development anyway).
